### ISSUE TITLE
Using PHP8 with xdebug 3.0 - xdebug_enable() undefined 

### ISSUE THREAD

**Issue by Aseksas** [sebastianbergmann/phpcpd#194] opened 2021-02-09 10:51 UTC
From xdebug update log - https://xdebug.org/docs/upgrade_guide 

xdebug 3.0 - xdebug_enable() function removed. Could you update code by it?

**Comment by sebastianbergmann** [comment] 2021-02-09 11:03
Duplicate of #191.

**Closed by sebastianbergmann** 2021-02-09 11:03 UTC
