### ISSUE TITLE
Command Argument --exclude Description missleading

### ISSUE THREAD

**Issue by floriant** [sebastianbergmann/phpcpd#108] opened 2014-11-03 12:39 UTC
Inside Command.php where the Command Arguments are defined, it says:

```
->addOption(
  'exclude',
  null,
  InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
  'Exclude a directory from code analysis (must be relative to source)'
)
```

However, the description is not correct. 
I have tested this Feature and found out that the Folder doesnt have to be Relative to Source.

My Test Example was searching for "vendor" Folders.
It found also the Folder "Configuration/vendor".
In fact, it found all Folders named "vendor" in the whole Project.

In my Opinion, it behaves like it should, from a usability perspective. But the Definition of the Argument should state that correctly.

**Comment by sebastianbergmann** [comment] 2017-01-24 08:08
Duplicate of #84.

**Closed by sebastianbergmann** 2017-01-24 08:08 UTC
