### ISSUE TITLE
Add info that exclude paths have to be relative to online help

### ISSUE THREAD

**Issue by DSB** [sebastianbergmann/phpcpd#77] opened 2013-09-14 07:52 UTC
I was struggling with the exclude param for a long time. Nothing seemed to work. The folders I mentioned in the exclude param weren't excluded. I wasted a lot of time until I found this little but important information here:

> Also note that the paths specified using --exclude have to be relative.

Please do add this to the cli help output. Please also add the info that you need to add one exclude param for each folder you want to exclude (instead of giving a a list).
Thanks.

Edit: it also doesn't work like expected using ant if there is a slash at the end of the directory value. It would be nice to have an example (excluding two dirs) call in the online help.

**Comment by sebastianbergmann** [comment] 2017-01-24 08:08
Duplicate of #84.

**Closed by sebastianbergmann** 2017-01-24 08:08 UTC
