### ISSUE TITLE
A new flag --ignore-violations-on-exit

### ISSUE THREAD

**Issue by hakamairi** [sebastianbergmann/phpcpd#154] opened 2017-11-20 10:02 UTC
Would it be possible for the phpcpd to add a new flag?
> --ignore-violations-on-exit

I use phpcpd as a tool for generating duplicate code reports. It would help a lot if the CLI call would be able to just "fail" on real error like Out Of Memory, since the ruleset for passing the build could be dependent on the result.

**Comment by sebastianbergmann** [comment] 2017-11-20 10:03
Duplicate of #148.

**Closed by sebastianbergmann** 2017-11-20 10:03 UTC
